version: '2.4'

networks:
    cloud-net:
        external: true
    # For local dns discovery
    home-net:
        external: true

volumes:
    redis_data:
        name: redis_data
    #postgres_data:
        #name: postgres_data
    #nextcloud_data:
        #name: nextcloud_data
        
services:          
    ###################################
    ############## redis ##############
    ###################################
    redis:
        image: redis
        container_name: redis
        hostname: redis
        restart: always
        command: "redis-server --requirepass ${REDIS_HOST_PASSWORD}"
        expose:
            - 6379
        networks:
            cloud-net:
                ipv4_address: 172.40.0.3
        volumes:
            - redis_data:/var/lib/redis  
        labels:
            - "com.centurylinklabs.watchtower.enable=true"
    ######################################
    ############## postgres ##############
    ######################################
    postgres:
        restart: always
        image: postgres:11
        container_name: postgres
        hostname: postgres
        networks:
            cloud-net:
                ipv4_address: 172.40.0.4
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB
        volumes:
            - ../data/cloud/postgres:/var/lib/postgresql/data:z
            
    #######################################
    ############## Collabora ##############
    #######################################
    collabora:
        image: collabora/code
        container_name: collabora
        hostname: collabora
        restart: unless-stopped
        networks:
            cloud-net:
                ipv4_address: 172.40.0.5
            home-net:
                ipv4_address: 172.0.0.6
        dns:
            - 172.0.0.4
        cap_add:
            - MKNOD
        expose:
            - 9980
        ports: 
            - "${COLLABORA_PORT}:9980"
        environment:
            domain: "cloud\\.${DOMAIN}"
            username: ${COLLABORA_ADMIN}
            password: ${COLLABORA_PASS}
            extra_params: --o:ssl.enable=false  --o:ssl.termination=true
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.collabora.entrypoints=http,https"
            - "traefik.http.routers.collabora.rule=Host(`collabora.${DOMAIN}`)"
            - "traefik.http.routers.collabora.tls=true"
            - "traefik.http.routers.collabora.service=collabora"
            - "traefik.http.services.collabora.loadbalancer.server.port=9980"
            - "traefik.http.routers.collabora.middlewares=collabora-sslheaders"
            - "traefik.http.middlewares.collabora-sslheaders.headers.customrequestheaders.X-Forwarded-Proto=https"
    
    #######################################
    ############## nextcloud ##############
    #######################################
    nextcloud:
        # Local image
        image: nextcloud:smb
        container_name: nextcloud
        hostname: cloud.${DOMAIN}
        restart: always
        networks:
            cloud-net:
                ipv4_address: 172.40.0.6
            home-net:
                ipv4_address: 172.0.0.7
        dns:
            # Adguard internal IP
            - 172.0.0.4
        expose:
            - 80
        ports:
            - "${NEXTCLOUD_PORT}:80"
        depends_on:
            - redis
            - postgres
            - collabora
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - REDIS_HOST_PASSWORD
            - POSTGRES_HOST=postgres
            - REDIS_HOST=redis
            - NEXTCLOUD_TRUSTED_DOMAINS="cloud.${DOMAIN},collabora.${DOMAIN}"
            - TRUSTED_PROXIES=172.40.0.2,172.0.0.2
            # SMPT Config
            - SMTP_HOST
            - SMTP_PORT
            - SMTP_SECURE
            - SMTP_AUTHTYPE
            - SMTP_NAME
            - SMTP_PASSWORD
            - MAIL_FROM_ADDRESS
            - MAIL_DOMAIN
        volumes:
            # if you don't want to manage your data localy then change this to docker volume
            - ../data/cloud/nextcloud:/var/www/html:rw
            # - nextcloud_data:/var/www/html
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.nextcloud.middlewares=nextcloud,nextcloud-caldav,nextcloud-sslheaders"
            - "traefik.http.routers.nextcloud.entrypoints=http,https"
            - "traefik.http.routers.nextcloud.rule=Host(`cloud.${DOMAIN}`)"
            - "traefik.http.routers.nextcloud.tls=true"
            - "traefik.http.routers.nextcloud.service=nextcloud"
            - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
            - "traefik.http.middlewares.nextcloud.headers.stsSeconds=155520011"
            - "traefik.http.middlewares.nextcloud.headers.customFrameOptionsValue=SAMEORIGIN"
            - "traefik.http.middlewares.nextcloud.headers.contentSecurityPolicy=upgrade-insecure-requests, frame-ancestors 'self' *.${DOMAIN} ${DOMAIN}"
            - "traefik.http.middlewares.nextcloud.headers.stsIncludeSubdomains=true"
            - "traefik.http.middlewares.nextcloud.headers.stsPreload=true"
            - "traefik.http.middlewares.nextcloud-caldav.redirectregex.permanent=true"
            - "traefik.http.middlewares.nextcloud-caldav.redirectregex.regex=^https://(.*)/.well-known/(card|cal)dav"
            - "traefik.http.middlewares.nextcloud-caldav.redirectregex.replacement=https://$${1}/remote.php/dav/"
            - "traefik.http.middlewares.nextcloud-sslheaders.headers.customrequestheaders.X-Forwarded-Proto=https"
            - "traefik.http.middlewares.nextcloud-sslheaders.headers.customResponseHeaders.X-Frame-Options=allow-from https://${DOMAIN}"
