version: '2.4'

networks:
    #########################################
    ############## Home bridge ##############
    #########################################
    home-net:
        name: home-net
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.0.0.0/16
                  gateway: 172.0.0.1
    ######################################################
    ############## Container manager bridge ##############
    ######################################################
    container-manager-net:
        name: container-manager-net
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.10.0.0/16
                  gateway: 172.10.0.1
    ##########################################
    ############## Media bridge ##############
    ##########################################
    media-net:
        name: media-net
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/16
                  gateway: 172.20.0.1

    ###############################################
    ############## Monitoring bridge ##############
    ###############################################
    monitor-net:
        name: monitor-net
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.30.0.0/16
                  gateway: 172.30.0.1
                  
    ##########################################
    ############## Cloud bridge ##############
    ##########################################
    cloud-net:
        name: cloud-net
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.40.0.0/16
                  gateway: 172.40.0.1
                  
services:   
    #####################################
    ############## traefik ##############
    #####################################
    traefik:
        image: traefik:v2.2
        container_name: traefik
        hostname: traefik
        restart: unless-stopped
        command:
            - "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
        environment:
            - DOMAIN
            - UTORRENT_URL
            - ROUTER_URL
        ports:
            - "80:80"
            - "443:443"
            - "${TRAEFIK_PORT}:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ../data/network/traefik/certs:/certs:ro
            - ../data/network/traefik/traefik.yml:/traefik.yml:ro
            - ../data/network/traefik/config:/config:ro
        networks:
            home-net:
                ipv4_address: 172.0.0.2
            container-manager-net:
                ipv4_address: 172.10.0.2
            media-net:
                ipv4_address: 172.20.0.2
            monitor-net:
                ipv4_address: 172.30.0.2
            cloud-net:
                ipv4_address: 172.40.0.2
        dns:
            - ${DNS1}
            - ${DNS2}
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.traefik.entrypoints=http,https"
            - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
            - "traefik.http.routers.traefik.tls=true"
            - "traefik.http.routers.traefik.service=api@internal"
            - "traefik.http.routers.traefik.middlewares=traefik-auth"
            - "traefik.http.services.traefik.loadbalancer.server.port=8080"
            - "traefik.http.middlewares.traefik-auth.basicauth.users=${BASIC_AUTH_USER}"
            - "com.centurylinklabs.watchtower.enable=true"

    ######################################
    ############## heimdall ##############
    ######################################
    heimdall:
        image: linuxserver/heimdall
        container_name: heimdall
        hostname: heimdall
        restart: unless-stopped
        ports:
            - "${HEIMDALL_PORT}:80"
        expose:
            - 80
        volumes:
            - ../data/network/heimdall:/config
        environment:
            PUID: 1000
            PGID: 1000
        networks:
            home-net:
                ipv4_address: 172.0.0.3
            container-manager-net:
                ipv4_address: 172.10.0.3
            media-net:
                ipv4_address: 172.20.0.3
            monitor-net:
                ipv4_address: 172.30.0.3
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.heimdall.entrypoints=http,https"
            - "traefik.http.routers.heimdall.rule=Host(`${DOMAIN}`)"
            - "traefik.http.routers.heimdall.tls=true"
            - "traefik.http.routers.heimdall.service=heimdall"
            - "traefik.http.services.heimdall.loadbalancer.server.port=80"
            - "com.centurylinklabs.watchtower.enable=true"
            
    #########################################
    ############## adguardhome ##############
    #########################################
    adguardhome:
        image: adguard/adguardhome
        container_name: adguardhome
        hostname: adguard
        restart: unless-stopped
        volumes:
            - ../data/network/adguard/work:/opt/adguardhome/work
            - ../data/network/adguard/conf:/opt/adguardhome/conf
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "67:67/udp"
            - "68:68/tcp"
            - "68:68/udp"
            - "4430:443/tcp"
            - "853:853/tcp"
            - "3001:3000/tcp"
            - "${ADGUARD_PORT}:8080/tcp"
        expose:
            - 53/tcp
            - 53/udp
            - 67/udp
            - 68/tcp
            - 68/udp
            - 853/tcp
        networks:
            home-net:
                ipv4_address: 172.0.0.4
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.adguard.entrypoints=http,https"
            - "traefik.http.routers.adguard.rule=Host(`adguard.${DOMAIN}`)"
            - "traefik.http.routers.adguard.tls=true"
            - "traefik.http.routers.adguard.service=adguard"
            - "traefik.http.services.adguard.loadbalancer.server.port=8080"
            - "com.centurylinklabs.watchtower.enable=true"
    
    #############################################
    ############## Static nautilus ##############
    #############################################
    nautilus:
        image: halverneus/static-file-server
        container_name: nautilus
        hostname: nautilus
        restart: unless-stopped
        volumes:
            - ../data/network/nautilus:/web
        ports:
            - "${NAUTILUS_PORT}:8080"
        expose:
            - 8080
        networks:
            home-net:
                ipv4_address: 172.0.0.5
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.nautilus.entrypoints=http,https"
            - "traefik.http.routers.nautilus.rule=Host(`nautilus.${DOMAIN}`)"
            - "traefik.http.routers.nautilus.tls=true"
            - "traefik.http.routers.nautilus.service=nautilus"
            - "traefik.http.services.nautilus.loadbalancer.server.port=8080"
            - "com.centurylinklabs.watchtower.enable=true"
